duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('GITHUB_WORKSPACE', '../') }}/dashboard/db/analysis_db.duckdb"
      database: analysis_db
      extensions:
        - parquet
        - httpfs