name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create database directories
        run: |
          mkdir -p dashboard/db
          mkdir -p dashboard/public/data
          mkdir -p account_analysis/target/data

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './dashboard/package-lock.json'

      - name: Install DBT dependencies
        working-directory: ./account_analysis
        run: dbt deps --profiles-dir .

      - name: Run DBT
        working-directory: ./account_analysis
        run: |
          dbt debug --profiles-dir .
          dbt seed --profiles-dir .
          dbt run --full-refresh --profiles-dir .

      - name: List generated files
        run: |
          echo "Content of target/data:"
          ls -la account_analysis/target/data || true
          echo "Content of dashboard/public/data:"
          ls -la dashboard/public/data || true
          echo "Content of dashboard/db:"
          ls -la dashboard/db || true

      - name: Install dashboard dependencies
        working-directory: ./dashboard
        run: npm ci

      - name: Setup data directories
        run: |
          cp -r account_analysis/target/data/* dashboard/public/data/ || true

      - name: Build dashboard
        working-directory: ./dashboard
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dashboard/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4